name = "medium"
compatibility_date = "2024-08-18"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGUyZDcyM2EtNDBjYi00ZGE3LTlkNTctNTVjMzY2M2I3ODg2IiwidGVuYW50X2lkIjoiMmQ1ODRiM2U1Yzk2MjcxZTdkNWI5ZjZlZDQ0NTY0MzUzMmJkZWE1NjNhYjRiODRiMmNiODQ5ZWI1YmQ0MmMxOSIsImludGVybmFsX3NlY3JldCI6ImZhOTJmNzI4LWJlNzQtNDgxOC1iMGRiLTBkZTRlZjA4YTllYyJ9.rvpIJAq2l1FZfaGdM_4BHxLYzEM5eqO5YShHY04bzz0"
JWT_SECRET = "secret"
